version: '3.8'

services:
  cleaner:
    build: .
    command: uvicorn services.data_cleaner.cleaner_controller:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  trainer:
    build: .
    command: uvicorn services.model_trainer.trainer_controller:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app

  predictor:
    build: .
    command: uvicorn services.prediction_server.predictor_controller:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    volumes:
      - .:/app

  evaluator:
    build: .
    command: uvicorn services.model_evaluator.evaluator_controller:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    volumes:
      - .:/app
  cache:
    build: .
    command: uvicorn services.result_cache.cache_controller:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    volumes:
      - .:/app
  # This service will run your main.py script after the others have started
  runner:
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - cleaner
      - trainer
      - predictor
      - evaluator
      - cache