version: '3.8'

services:
  cleaner:
    build:
      context: .
      args:
        - SERVICE_PATH=services/data_cleaner
    command: uvicorn services.data_cleaner.cleaner_controller:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./services/data_cleaner:/app/services/data_cleaner

  trainer:
    build:
      context: .
      args:
        - SERVICE_PATH=services/model_trainer
    command: uvicorn services.model_trainer.trainer_controller:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - ./services/model_trainer:/app/services/model_trainer

  predictor:
    build:
      context: .
      args:
        - SERVICE_PATH=services/prediction_server
    command: uvicorn services.prediction_server.predictor_controller:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    volumes:
      - ./services/prediction_server:/app/services/prediction_server

  evaluator:
    build:
      context: .
      args:
        - SERVICE_PATH=services/model_evaluator
    command: uvicorn services.model_evaluator.evaluator_controller:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    volumes:
      - ./services/model_evaluator:/app/services/model_evaluator

  cache:
    build:
      context: .
      args:
        - SERVICE_PATH=services/result_cache
    command: uvicorn services.result_cache.cache_controller:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    volumes:
      - ./services/result_cache:/app/services/result_cache

  # This service now uses its own minimal Dockerfile
  runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    volumes:
      - ./main.py:/app/main.py
      - ./Intelligence_Selection.csv:/app/Intelligence_Selection.csv
    depends_on:
      - cleaner
      - trainer
      - predictor
      - evaluator
      - cache